config/routes.rb
AuthorityDemo::Application.routes.draw do

  get '/roles' => 'roles#index'
  get '/roles/:name/edit' => 'roles#edit', :as => 'edit_role'
  get '/roles/:name' => 'roles#show', :as => 'role'
  put '/roles/:name' => 'roles#update', :as => 'update_role'

  root :to => "roles#index"

end

app/models/authority.rb
class Authority
  attr_reader :name, :group
  @@all = {}

  # This method is used by :belongs_to in AuthorityRole, and
  # is called with an array in Role#update
  def self.find_by_name(name, conditions=nil)
    if name.class == Array
      @@all.values.select {|a| name.include? a.name}
    else
      @@all[name]
    end  
  end

  def self.all
    @@all.values
  end

  def initialize(name, group)
    @name = name
    @group = group
    @@all[name] = self
  end

  self.new "Create User", "Users"
  self.new "Delete User", "Users"
  self.new "Update User", "Users"
  self.new "View Reports", "Reports"
end

app/models/authority_role.rb
class AuthorityRole < ActiveRecord::Base
  belongs_to :role, :primary_key => :name, :foreign_key => :role_name
  belongs_to :authority, :primary_key => :name, :foreign_key => :authority_name
end

app/models/role.rb
class Role
  extend ActiveModel::Naming  # needed to render form in edit view

  attr_accessor :name
  @@all = {}

  # This is used by belongs_to in AuthorityRoles, as well as its use
  # in RolesController
  def self.find_by_name(name, conditions=nil)
    @@all[name]
  end

  def self.all
    @@all.values
  end

  def initialize(name)
    @name = name
    @@all[name] = self
  end

  def authorities
    AuthorityRole.where(:role_name => self.name).collect {|ar| ar.authority}
  end

  # Imitates has_many :authorities, :through => :authority_roles, which
  # can't be done easily since this is not an ActiveRecord class
  def authorities=(authorities)
    AuthorityRole.delete_all(:role_name => self.name)
    if authorities
      for authority in authorities
        AuthorityRole.new(:role_name => self.name,
                          :authority_name => authority.name).save
      end
    end
  end

  self.new "Admin"
  self.new "Reports"
  self.new "CSR"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/Admin
  # GET /roles/Admin.xml
  def show
    @role = Role.find_by_name(params[:name])
    @role_authorities = @role.authorities

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/Admin/edit
  def edit
    @role = Role.find_by_name(params[:name])
    @all_authorities = Authority.all
  end

  # PUT /roles/Admin
  # PUT /roles/Admin.xml
  # This only updates AuthorityRole, not Role. It always succeeds (or at
  # least it fails silently).
  def update
    @role = Role.find_by_name(params[:name])

    respond_to do |format|
      @role.authorities = Authority.find_by_name(params[:authority_names])
      format.html { redirect_to(role_path(@role.name),
           :notice => 'Role was successfully updated.') }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authority Demo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/roles/_form.html.erb
<% # This uses form_tag instead of form_for, because the latter requires
   # too much extra baggage in Role %>

<%= form_tag update_role_path(@role.name), :method => :put do |f| %>
  <div class="field">
    <%= label_tag 'name' %>:
    <%= @role.name %>
  </div>

  <% for authority in @all_authorities %>
    <div class="field">
      <%= check_box_tag "authority_names[]", authority.name,
                        checked = @role.authorities.include?(authority) %>
      <%= label_tag authority.name %>
    </div>
  <% end %>
 
  <div class="actions">
    <%= submit_tag 'Update Role' %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', role_path(@role.name) %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role_path(role.name) %></td>
    <td><%= link_to 'Edit', edit_role_path(role.name) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>

<p>
  <b>Role Authorities:</b>
  <%= @role_authorities.collect {|a| a.name }.join(', ') %>
</p>

<%= link_to 'Edit', edit_role_path(@role.name) %> |
<%= link_to 'Back', roles_path %>